### ISSUE TITLE
Add missing essential files.

### ISSUE THREAD

**Issue by Avi-E-Koenig** [Kishurit/Kishurit-Server#1]
Hi,

Upon preliminary inspection the project is missing some basic files:

- readme.md
Show project description and install instructions
- .gitignore
exclude irrelevant files.
- .env.locl.example
template including used env vars in project.

**Comment by romanbr87** [comment]
Thanks for your comment. You are right in everything you wrote. Right now, no one is working on the code except me. I need to finish handling the database and then I can handle the information. In the meantime I can update some of the relevant information

**Comment by Avi-E-Koenig** [comment]
DM on discord we will discuss this further.
